### ISSUE TITLE
Research SQLite API in C++

### ISSUE THREAD

**Issue by petrik33** [fpmi-tp2023/labrabota5pr2-fluffy-kittens#7]
Тут на русском, чтобы понятно было: посмотри плиз, как в C++ пользоваться SQLite, потом я когда создам методы нужные реализуем в них вместе запросы и их отображение в UI

**Comment by artyomshpakovski** [comment]
:+1:

**Comment by artyomshpakovski** [comment]
Накину пару источников, которые нашел:
1. Явные примеры кода
https://www.tutorialspoint.com/sqlite/sqlite_c_cpp.htm
2. Больше описательный характер
https://www.sqlite.org/cintro.html
3. Еще пара источников:
https://www.geeksforgeeks.org/sql-using-c-c-and-sqlite/
https://github.com/SRombauts/SQLiteCpp/tree/master/examples
